(cl:defpackage mav_planning_msgs-srv
  (:use )
  (:export
   "POLYGONSERVICE"
   "<POLYGONSERVICE-REQUEST>"
   "POLYGONSERVICE-REQUEST"
   "<POLYGONSERVICE-RESPONSE>"
   "POLYGONSERVICE-RESPONSE"
   "PLANNERSERVICE"
   "<PLANNERSERVICE-REQUEST>"
   "PLANNERSERVICE-REQUEST"
   "<PLANNERSERVICE-RESPONSE>"
   "PLANNERSERVICE-RESPONSE"
  ))

